# Cleaning University of California Berkeley Power Consumption Dataset

The data retrieved from [UCB's energy dashboard](https://engagementdashboard.com/ucb/ucb) regarding power consumption in UCB's Mechanical Engineering building is in the form of a `json` format. Here we'll be converting it into a `csv` file for later data analysis.

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import json
import pprint
from datetime import datetime

In [29]:
filename = 'Datasets/Princeton Power Data/buildings-2019-'
df_power = pd.DataFrame()
for i in range(1,13):
    month_power = pd.read_csv(filename + str(i))
    df_power = df_power.append(month_power)
    
df_power = df_power[df_power['1915Hall.kWh'] != 'None']
df_power.to_csv('Datasets/Princeton_PowerConsumption.csv', index=False)
df_power.describe()

,Time (UTC),1915Hall.kW,1915Hall.kWh,1927Hall.kW,1927Hall.kWh,1937Feinberg.kW,1937Feinberg.kWh,1938Hall.kW,1938Hall.kWh,1939Hall.kW,...,Rocky.wv.kW,Rocky.wv.kWh,Whitman.kW,Whitman.kWh,Wilcox.kW,Wilcox.kWh,Wilson.wv.kW,Wilson.wv.kWh,Witherspoon.kW,Witherspoon.kWh
count,8748,8748,8748,8748,8748,8748,8748,8748,8748,8748,...,8748,8748,8748,8748,8748,8748,8748,8748,8748,8748
unique,8748,1002,8748,4643,8748,8633,8746,3585,8748,5560,...,8740,8748,8251,8748,8701,8747,8745,8748,6838,8742
top,2019-07-17T14:00:00Z,9.01666666667,400527,11.435,467883,8.73886666667,2868.335,5.49333333333,287724,6.09666666667,...,85.7289768977,7128053.24752,214.006666667,26112168,184.196666667,43593.754,107.4639,2112469.98,12.35,1029
freq,1,93,1,9,1,3,2,13,1,9,...,2,1,4,1,2,2,2,1,8,7